ALTER TABLE List DROP CONSTRAINT "UQ_LIST_COL_INDEX";
ALTER TABLE List ADD CONSTRAINT "UQ_LIST_COL_INDEX" UNIQUE("index") DEFERRABLE;

ALTER TABLE Card DROP CONSTRAINT "UQ_CARD_COL_INDEX";
ALTER TABLE Card ADD CONSTRAINT "UQ_CARD_COL_INDEX" UNIQUE("listId", "index") DEFERRABLE;